### ISSUE TITLE
RealBench Crash Issue

### ISSUE THREAD

**Issue by Bvioto** [RenEvo/pcb#16]
I got this: 

_The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Attempted to get the ID for a unknown recipe: net.minecraft.item.crafting.ShapelessRecipes@11e11bf5 Name: pcb:portable_craft_bench_

This is the crash report:

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
  BCModPlugin (backpacks+1.12.2+-+3.4.4.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 4/14/18 1:07 PM
Description: Unexpected error

java.lang.IllegalArgumentException: Attempted to get the ID for a unknown recipe: net.minecraft.item.crafting.ShapelessRecipes@11e11bf5 Name: pcb:portable_craft_bench
	at net.minecraft.stats.RecipeBook.func_194075_d(RecipeBook.java:53)
	at net.minecraft.stats.RecipeBook.func_193830_f(RecipeBook.java:35)
	at net.minecraft.client.gui.recipebook.RecipeList.func_194210_a(SourceFile:34)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook.lambda$updateCollections$0(GuiRecipeBook.java:161)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook$$Lambda$222/1249420827.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook.func_193003_g(GuiRecipeBook.java:159)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook.func_193014_a(GuiRecipeBook.java:96)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook.func_194303_a(GuiRecipeBook.java:73)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73866_w_(SourceFile:52)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:478)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1016)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2173)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2018)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1806)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.stats.RecipeBook.func_194075_d(RecipeBook.java:53)
	at net.minecraft.stats.RecipeBook.func_193830_f(RecipeBook.java:35)
	at net.minecraft.client.gui.recipebook.RecipeList.func_194210_a(SourceFile:34)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook.lambda$updateCollections$0(GuiRecipeBook.java:161)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook$$Lambda$222/1249420827.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook.func_193003_g(GuiRecipeBook.java:159)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook.func_193014_a(GuiRecipeBook.java:96)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook.func_194303_a(GuiRecipeBook.java:73)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73866_w_(SourceFile:52)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:478)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1016)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2173)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2018)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['bvioto'/195, l='MpServer', x=11.24, y=79.56, z=-45.59]]
	Chunk stats: MultiplayerChunkCache: 379, 379
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (132,64,252), Chunk: (at 4,4,12 in 8,15; contains blocks 128,0,240 to 143,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 4445988 game time, 4445988 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 86 total; [EntityPlayerSP['bvioto'/195, l='MpServer', x=11.24, y=79.56, z=-45.59], EntityItem['item.item.egg'/384, l='MpServer', x=73.49, y=96.00, z=-77.73], EntityLatchedRenderer['Entidad desconocida'/1, l='MpServer', x=11.24, y=79.56, z=-45.59], EntityChicken['Gallina'/388, l='MpServer', x=88.36, y=80.00, z=-85.53], EntityChicken['Gallina'/389, l='MpServer', x=88.89, y=80.00, z=-85.35], EntitySkeleton['Esqueleto'/391, l='MpServer', x=44.50, y=62.00, z=-39.50], EntitySheep['Oveja'/392, l='MpServer', x=44.27, y=82.00, z=-63.51], EntityChicken['Gallina'/393, l='MpServer', x=65.49, y=95.00, z=-89.20], EntityEnderman['Enderman'/266, l='MpServer', x=-28.50, y=18.00, z=-30.50], EntityPig['Cerdo'/394, l='MpServer', x=26.25, y=76.00, z=31.50], EntityBat['Murciélago'/267, l='MpServer', x=-30.44, y=19.03, z=-28.71], EntityPig['Cerdo'/395, l='MpServer', x=26.51, y=79.00, z=23.67], EntitySpider['Araña'/268, l='MpServer', x=-36.50, y=27.00, z=-1.50], EntityPig['Cerdo'/396, l='MpServer', x=22.53, y=77.00, z=27.75], EntityPig['Cerdo'/397, l='MpServer', x=19.50, y=78.00, z=23.75], EntityBat['Murciélago'/271, l='MpServer', x=7.73, y=45.00, z=4.10], EntitySkeleton['Esqueleto'/272, l='MpServer', x=8.55, y=45.00, z=4.00], EntityZombie['Zombi'/273, l='MpServer', x=11.49, y=44.00, z=2.25], EntityBat['Murciélago'/276, l='MpServer', x=10.38, y=53.46, z=28.58], EntityCreeper['Creeper'/278, l='MpServer', x=-25.50, y=20.00, z=24.50], EntityCreeper['Creeper'/279, l='MpServer', x=-24.50, y=20.00, z=25.50], EntityCreeper['Creeper'/280, l='MpServer', x=-24.50, y=20.00, z=24.50], EntitySheep['Oveja'/408, l='MpServer', x=61.34, y=72.00, z=-119.80], EntitySheep['Oveja'/409, l='MpServer', x=63.22, y=71.00, z=-122.53], EntityZombie['Zombi'/283, l='MpServer', x=-39.50, y=16.00, z=31.50], EntityCreeper['Creeper'/284, l='MpServer', x=-46.50, y=22.00, z=31.50], EntityZombie['Zombi'/291, l='MpServer', x=9.50, y=54.00, z=32.50], EntityChicken['Gallina'/293, l='MpServer', x=-2.34, y=90.00, z=-93.15], EntityChicken['Gallina'/294, l='MpServer', x=-0.50, y=90.00, z=-95.50], EntityItem['item.item.egg'/295, l='MpServer', x=-1.27, y=90.00, z=-94.86], EntitySkeleton['Esqueleto'/296, l='MpServer', x=-30.50, y=32.00, z=-74.50], EntitySheep['Oveja'/297, l='MpServer', x=-21.19, y=71.00, z=-67.69], EntityChicken['Gallina'/298, l='MpServer', x=2.88, y=92.00, z=-99.51], EntityChicken['Gallina'/299, l='MpServer', x=-1.50, y=92.00, z=-110.50], EntityChicken['Gallina'/300, l='MpServer', x=-1.50, y=92.00, z=-110.50], EntityChicken['Gallina'/301, l='MpServer', x=-1.50, y=92.00, z=-110.50], EntityChicken['Gallina'/302, l='MpServer', x=-1.50, y=90.00, z=-96.77], EntityItem['item.item.egg'/303, l='MpServer', x=-2.11, y=90.00, z=-96.88], EntityZombie['Zombi'/432, l='MpServer', x=82.50, y=28.00, z=-46.50], EntityItem['item.item.egg'/305, l='MpServer', x=-2.90, y=90.00, z=-109.44], EntityZombie['Zombi'/433, l='MpServer', x=84.50, y=28.00, z=-46.50], EntityCreeper['Creeper'/306, l='MpServer', x=-21.47, y=30.00, z=-44.83], EntityEnderman['Enderman'/307, l='MpServer', x=-27.50, y=18.00, z=-33.50], EntityBat['Murciélago'/308, l='MpServer', x=-18.43, y=36.10, z=-46.25], EntityBat['Murciélago'/309, l='MpServer', x=-21.99, y=33.03, z=-42.25], EntityCreeper['Creeper'/310, l='MpServer', x=-34.50, y=18.00, z=-22.50], EntitySheep['Oveja'/311, l='MpServer', x=-34.44, y=70.00, z=-23.19], EntityCreeper['Creeper'/312, l='MpServer', x=-13.50, y=20.00, z=-52.50], EntitySkeleton['Esqueleto'/313, l='MpServer', x=-15.50, y=19.00, z=-51.50], EntitySkeleton['Esqueleto'/314, l='MpServer', x=-15.50, y=19.00, z=-51.50], EntityBat['Murciélago'/315, l='MpServer', x=-8.84, y=20.56, z=-57.87], EntityCreeper['Creeper'/316, l='MpServer', x=10.50, y=18.00, z=-81.50], EntitySkeleton['Esqueleto'/317, l='MpServer', x=-14.50, y=13.00, z=-65.50], EntityCreeper['Creeper'/318, l='MpServer', x=-0.50, y=14.00, z=-70.50], EntityCreeper['Creeper'/319, l='MpServer', x=-19.50, y=21.00, z=-58.50], EntitySkeleton['Esqueleto'/320, l='MpServer', x=-25.24, y=19.00, z=-49.59], EntitySkeleton['Esqueleto'/321, l='MpServer', x=-16.68, y=19.00, z=-57.49], EntitySkeleton['Esqueleto'/322, l='MpServer', x=-17.50, y=19.00, z=-53.50], EntitySheep['Oveja'/323, l='MpServer', x=-28.45, y=72.00, z=-57.21], EntityBat['Murciélago'/328, l='MpServer', x=-14.40, y=24.03, z=-120.78], EntityBat['Murciélago'/329, l='MpServer', x=-15.56, y=24.10, z=-119.80], EntityChicken['Gallina'/330, l='MpServer', x=-0.69, y=91.00, z=-116.13], EntityBat['Murciélago'/356, l='MpServer', x=69.75, y=32.91, z=-26.46], EntitySkeleton['Esqueleto'/357, l='MpServer', x=87.50, y=40.00, z=-114.50], EntitySkeleton['Esqueleto'/358, l='MpServer', x=88.50, y=40.00, z=-115.50], EntitySheep['Oveja'/235, l='MpServer', x=-60.44, y=80.00, z=-96.82], EntitySheep['Oveja'/236, l='MpServer', x=-66.22, y=78.00, z=-87.71], EntityChicken['Gallina'/364, l='MpServer', x=61.50, y=95.00, z=-82.50], EntityChicken['Gallina'/365, l='MpServer', x=56.85, y=95.00, z=-87.17], EntityItem['item.item.egg'/366, l='MpServer', x=61.24, y=95.00, z=-82.80], EntitySheep['Oveja'/239, l='MpServer', x=-64.99, y=81.00, z=-100.80], EntityItem['item.item.egg'/367, l='MpServer', x=56.18, y=95.00, z=-87.53], EntityZombie['Zombi'/368, l='MpServer', x=54.50, y=29.00, z=6.50], EntityZombie['Zombi'/241, l='MpServer', x=-58.50, y=32.00, z=-79.50], EntitySkeleton['Esqueleto'/369, l='MpServer', x=56.50, y=29.00, z=6.50], EntitySkeleton['Esqueleto'/370, l='MpServer', x=55.50, y=29.00, z=8.50], EntityBat['Murciélago'/371, l='MpServer', x=54.46, y=29.64, z=6.52], EntityCreeper['Creeper'/372, l='MpServer', x=60.50, y=37.00, z=-111.50], EntityCreeper['Creeper'/373, l='MpServer', x=55.50, y=37.00, z=-109.50], EntityCreeper['Creeper'/378, l='MpServer', x=41.88, y=60.00, z=-26.79], EntitySkeleton['Esqueleto'/379, l='MpServer', x=41.50, y=61.00, z=-17.79], EntitySkeleton['Esqueleto'/380, l='MpServer', x=36.78, y=60.00, z=-16.51], EntitySkeleton['Esqueleto'/253, l='MpServer', x=-48.50, y=22.00, z=33.50], EntitySkeleton['Esqueleto'/381, l='MpServer', x=40.30, y=60.00, z=-25.78], EntitySheep['Oveja'/382, l='MpServer', x=56.50, y=77.00, z=-44.77], EntityChicken['Gallina'/383, l='MpServer', x=74.10, y=96.00, z=-78.19]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 874010504 bytes (833 MB) / 1442840576 bytes (1376 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.2.2629 15 mods loaded, 15 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version       | Source                              | Signature                                |
	|:------ |:----------------- |:------------- |:----------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft         | 1.12.2        | minecraft.jar                       | None                                     |
	| UCHIJA | mcp               | 9.42          | minecraft.jar                       | None                                     |
	| UCHIJA | FML               | 8.0.99.99     | forge-1.12.2-14.23.2.2629.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge             | 14.23.2.2629  | forge-1.12.2-14.23.2.2629.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | mercurius_updater | 1.0           | MercuriusUpdater-1.12.2.jar         | None                                     |
	| UCHIJA | backpacks16840    | 3.4.4         | backpacks+1.12.2+-+3.4.4.jar        | None                                     |
	| UCHIJA | carryon           | 1.7.2         | CarryOn+MC1.12.2+v1.7.2.jar         | None                                     |
	| UCHIJA | waila             | 1.8.20        | Hwyla-1.8.20-B35_1.12.jar           | None                                     |
	| UCHIJA | ichunutil         | 7.1.4         | iChunUtil-1.12.2-7.1.4.jar          | None                                     |
	| UCHIJA | jei               | 4.8.5.159     | jei_1.12.2-4.8.5.159.jar            | None                                     |
	| UCHIJA | justenoughbuttons | 1.12-1.2.1    | justenoughbuttons-1.12-1.2.1.jar    | None                                     |
	| UCHIJA | mobdismemberment  | 7.0.0         | MobDismemberment-1.12.2-7.0.0.jar   | None                                     |
	| UCHIJA | pcb               | 1.5.0         | portablecraftbench-1.12.2-1.5.1.jar | None                                     |
	| UCHIJA | soundfilters      | 0.10_for_1.12 | SoundFilters-0.10_for_1.12.jar      | None                                     |
	| UCHIJA | xaerominimap      | 1.15          | Xaeros_Minimap_1.15_Forge_1.12.jar  | None                                     |

	Loaded coremods (and transformers): 
RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
  pw.prok.realbench.asm.RBTransformer
BCModPlugin (backpacks+1.12.2+-+3.4.4.jar)
  brad16840.core.ClassTransformer
	Launched Version: 1.12.2-forge1.12.2-14.23.2.2629
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.43, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: paper_cutout_3_71859379.zip
	Current Language: Español (México)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz`

I don't know what went wrong but I thought it has something to do with Portable Craft Bench Mod.

**Comment by renevo** [comment]
Looks to be a conflict with realbench.
