### ISSUE TITLE
Error when sorting with Inventory Tweaks

### ISSUE THREAD

**Issue by RenEvo** [RenEvo/pcb#7]
Inventory Tweaks spams errors when you try to middle-click sort the inventory.

```
[23:06:44] [Client thread/INFO] [STDERR/]: [invtweaks.InvTweaks:logInGameError:467]: java.lang.IndexOutOfBoundsException: Index: 35, Size: 35
[23:06:44] [Client thread/INFO] [STDERR/]: [invtweaks.InvTweaks:logInGameError:467]: 	at java.util.ArrayList$SubList.rangeCheck(ArrayList.java:1217)
[23:06:44] [Client thread/INFO] [STDERR/]: [invtweaks.InvTweaks:logInGameError:467]: 	at java.util.ArrayList$SubList.get(ArrayList.java:1034)
[23:06:44] [Client thread/INFO] [STDERR/]: [invtweaks.InvTweaks:logInGameError:467]: 	at invtweaks.container.DirectContainerManager.indexToSlot(DirectContainerManager.java:366)
[23:06:44] [Client thread/INFO] [STDERR/]: [invtweaks.InvTweaks:logInGameError:467]: 	at invtweaks.container.DirectContainerManager.getItemStack(DirectContainerManager.java:329)
[23:06:44] [Client thread/INFO] [STDERR/]: [invtweaks.InvTweaks:logInGameError:467]: 	at invtweaks.container.ContainerSectionManager.getItemStack(ContainerSectionManager.java:72)
[23:06:44] [Client thread/INFO] [STDERR/]: [invtweaks.InvTweaks:logInGameError:467]: 	at invtweaks.InvTweaksHandlerSorting.mergeItem(InvTweaksHandlerSorting.java:283)
[23:06:44] [Client thread/INFO] [STDERR/]: [invtweaks.InvTweaks:logInGameError:467]: 	at invtweaks.InvTweaksHandlerSorting.sortMergeArmor(InvTweaksHandlerSorting.java:273)
[23:06:44] [Client thread/INFO] [STDERR/]: [invtweaks.InvTweaks:logInGameError:467]: 	at invtweaks.InvTweaksHandlerSorting.sortInventory(InvTweaksHandlerSorting.java:255)
[23:06:44] [Client thread/INFO] [STDERR/]: [invtweaks.InvTweaks:logInGameError:467]: 	at invtweaks.InvTweaksHandlerSorting.sort(InvTweaksHandlerSorting.java:144)
[23:06:44] [Client thread/INFO] [STDERR/]: [invtweaks.InvTweaks:logInGameError:467]: 	at invtweaks.InvTweaks.handleSorting(InvTweaks.java:604)
[23:06:44] [Client thread/INFO] [STDERR/]: [invtweaks.InvTweaks:logInGameError:467]: 	at invtweaks.InvTweaks.handleMiddleClick(InvTweaks.java:758)
[23:06:44] [Client thread/INFO] [STDERR/]: [invtweaks.InvTweaks:logInGameError:467]: 	at invtweaks.InvTweaks.onTickInGUI(InvTweaks.java:200)
[23:06:44] [Client thread/INFO] [STDERR/]: [invtweaks.InvTweaks:logInGameError:467]: 	at invtweaks.forge.ForgeClientTick.onTick(ForgeClientTick.java:22)
[23:06:44] [Client thread/INFO] [STDERR/]: [invtweaks.InvTweaks:logInGameError:467]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_72_ForgeClientTick_onTick_ClientTickEvent.invoke(.dynamic)
[23:06:44] [Client thread/INFO] [STDERR/]: [invtweaks.InvTweaks:logInGameError:467]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
[23:06:44] [Client thread/INFO] [STDERR/]: [invtweaks.InvTweaks:logInGameError:467]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
[23:06:44] [Client thread/INFO] [STDERR/]: [invtweaks.InvTweaks:logInGameError:467]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:331)
[23:06:44] [Client thread/INFO] [STDERR/]: [invtweaks.InvTweaks:logInGameError:467]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1624)
[23:06:44] [Client thread/INFO] [STDERR/]: [invtweaks.InvTweaks:logInGameError:467]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
[23:06:44] [Client thread/INFO] [STDERR/]: [invtweaks.InvTweaks:logInGameError:467]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
[23:06:44] [Client thread/INFO] [STDERR/]: [invtweaks.InvTweaks:logInGameError:467]: 	at net.minecraft.client.main.Main.main(SourceFile:124)
[23:06:44] [Client thread/INFO] [STDERR/]: [invtweaks.InvTweaks:logInGameError:467]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:06:44] [Client thread/INFO] [STDERR/]: [invtweaks.InvTweaks:logInGameError:467]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23:06:44] [Client thread/INFO] [STDERR/]: [invtweaks.InvTweaks:logInGameError:467]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:06:44] [Client thread/INFO] [STDERR/]: [invtweaks.InvTweaks:logInGameError:467]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[23:06:44] [Client thread/INFO] [STDERR/]: [invtweaks.InvTweaks:logInGameError:467]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[23:06:44] [Client thread/INFO] [STDERR/]: [invtweaks.InvTweaks:logInGameError:467]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by RenEvo** [comment]
Looks like it got fixed with Inv Tweaks update.
